from datetime import datetime
from html import escape

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.models.report import Report
from app.models.tender import TenderAnalysis
from app.services.pdf_report import build_tender_pdf, build_text_pdf


router = APIRouter(
    prefix="/api/reports",
    tags=["Reports"],
)


def serialize_report(report: Report):
    return {
        "id": report.id,
        "tender_id": report.tender_id,
        "report_type": report.report_type,
        "title": report.title,
        "content": report.content,
        "created_at": report.created_at.isoformat()
        if report.created_at
        else None,
    }


def build_report_content(tender: TenderAnalysis):
    findings = tender.findings or []
    sources = tender.sources or []

    lines = []

    lines.append("BISQ COMPLIANCE REPORT")
    lines.append("=" * 80)
    lines.append("")

    lines.append(f"Tender: {tender.filename or 'Untitled Tender'}")
    lines.append(f"Analysis ID: {tender.id}")
    lines.append(
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC"
    )
    lines.append("")

    lines.append("OVERALL STATUS")
    lines.append("-" * 80)
    lines.append(tender.status or "NEEDS_EVIDENCE")
    lines.append("")

    lines.append("SUMMARY")
    lines.append("-" * 80)
    lines.append(tender.summary or "No summary available.")
    lines.append("")

    lines.append("FINDINGS")
    lines.append("-" * 80)

    if not findings:
        lines.append("No findings were generated.")
    else:
        for index, finding in enumerate(findings, start=1):
            requirement = finding.get("requirement", "")
            assessment = finding.get("assessment", "")
            evidence = finding.get("evidence", "")
            source = finding.get("source", "")
            page = finding.get("page")

            lines.append(f"{index}. Requirement")
            lines.append(requirement)

            lines.append("")
            lines.append("Assessment")
            lines.append(assessment)

            lines.append("")
            lines.append("Evidence")
            lines.append(evidence)

            if source:
                lines.append("")
                lines.append(f"Source: {source}")

            if page is not None:
                lines.append(f"Page: {page}")

            lines.append("")
            lines.append("-" * 80)

    lines.append("")
    lines.append("BIS SOURCES")
    lines.append("-" * 80)

    if not sources:
        lines.append("No BIS sources available.")
    else:
        for index, source in enumerate(sources, start=1):
            lines.append(
                f"{index}. "
                f"{source.get('is_number') or source.get('document_id') or 'Unknown'}"
            )

            title = source.get("title")
            year = source.get("year")
            page = source.get("page_number")
            pdf_url = source.get("pdf_url")

            if title:
                lines.append(f"Title: {title}")

            if year:
                lines.append(f"Year: {year}")

            if page is not None:
                lines.append(f"Page: {page}")

            if pdf_url:
                lines.append(f"PDF: {pdf_url}")

            lines.append("")

    lines.append("=" * 80)
    lines.append("Generated by BISQ")
    lines.append("")

    return "\n".join(lines)


def build_html_report(tender: TenderAnalysis):
    findings = tender.findings or []
    sources = tender.sources or []

    status = escape(tender.status or "NEEDS_EVIDENCE")
    filename = escape(tender.filename or "Untitled Tender")
    summary = escape(tender.summary or "No summary available.")

    finding_html = ""

    if not findings:
        finding_html = "<p>No findings were generated.</p>"
    else:
        for index, finding in enumerate(findings, start=1):
            requirement = escape(
                str(finding.get("requirement", ""))
            )
            assessment = escape(
                str(finding.get("assessment", ""))
            )
            evidence = escape(
                str(finding.get("evidence", ""))
            )
            source = escape(
                str(finding.get("source", ""))
            )

            page = finding.get("page")

            page_html = (
                f"<p><strong>Page:</strong> {escape(str(page))}</p>"
                if page is not None
                else ""
            )

            source_html = (
                f"<p><strong>Source:</strong> {source}</p>"
                if source
                else ""
            )

            finding_html += f"""
            <section class="finding">
                <h3>Finding {index}</h3>

                <h4>Requirement</h4>
                <p>{requirement}</p>

                <h4>Assessment</h4>
                <p>{assessment}</p>

                <h4>Evidence</h4>
                <p>{evidence}</p>

                {source_html}
                {page_html}
            </section>
            """

    source_html = ""

    if not sources:
        source_html = "<p>No BIS sources available.</p>"
    else:
        for index, source in enumerate(sources, start=1):
            number = escape(
                str(
                    source.get("is_number")
                    or source.get("document_id")
                    or "Unknown"
                )
            )

            title = escape(str(source.get("title") or ""))
            year = escape(str(source.get("year") or ""))
            page = source.get("page_number")
            pdf_url = source.get("pdf_url")

            pdf_html = ""

            if pdf_url:
                safe_url = escape(str(pdf_url), quote=True)
                pdf_html = (
                    f'<p><a href="{safe_url}" target="_blank">'
                    "Open BIS PDF</a></p>"
                )

            source_html += f"""
            <section class="source">
                <h3>Source {index}: {number}</h3>
                <p><strong>Title:</strong> {title}</p>
                <p><strong>Year:</strong> {year}</p>
                <p><strong>Page:</strong> {
                    escape(str(page)) if page is not None else "N/A"
                }</p>
                {pdf_html}
            </section>
            """

    generated_at = datetime.utcnow().strftime(
        "%Y-%m-%d %H:%M:%S UTC"
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BISQ Compliance Report</title>

    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 1000px;
            margin: 40px auto;
            padding: 0 24px;
            line-height: 1.6;
            color: #222;
        }}

        h1 {{
            margin-bottom: 5px;
        }}

        h2 {{
            margin-top: 40px;
            border-bottom: 2px solid #ddd;
            padding-bottom: 8px;
        }}

        h3 {{
            margin-top: 0;
        }}

        h4 {{
            margin-bottom: 4px;
        }}

        .meta {{
            color: #666;
            margin-bottom: 30px;
        }}

        .status {{
            display: inline-block;
            padding: 8px 14px;
            border-radius: 6px;
            font-weight: bold;
            background: #eee;
        }}

        .summary {{
            background: #f6f6f6;
            padding: 18px;
            border-radius: 8px;
        }}

        .finding,
        .source {{
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 18px 0;
        }}

        a {{
            color: #0645ad;
        }}

        footer {{
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #777;
        }}

        @media print {{
            body {{
                margin: 0;
                max-width: none;
            }}

            .finding,
            .source {{
                break-inside: avoid;
            }}
        }}
    </style>
</head>

<body>

    <h1>BISQ Compliance Report</h1>

    <div class="meta">
        <strong>Tender:</strong> {filename}<br>
        <strong>Analysis ID:</strong> {tender.id}<br>
        <strong>Generated:</strong> {generated_at}
    </div>

    <h2>Overall Status</h2>

    <div class="status">
        {status}
    </div>

    <h2>Summary</h2>

    <div class="summary">
        {summary}
    </div>

    <h2>Findings</h2>

    {finding_html}

    <h2>BIS Sources</h2>

    {source_html}

    <footer>
        Generated by BISQ
    </footer>

</body>
</html>
"""


@router.get("")
def get_reports(
    db: Session = Depends(get_db),
):
    reports = (
        db.query(Report)
        .order_by(Report.created_at.desc())
        .all()
    )

    return {
        "count": len(reports),
        "reports": [
            serialize_report(report)
            for report in reports
        ],
    }


@router.post("/generate")
def generate_report(
    type: str = Query(
        "compliance",
        min_length=1,
    ),
    tender_id: int | None = Query(
        None,
        ge=1,
    ),
    db: Session = Depends(get_db),
):
    if type not in {"compliance", "tender_summary"}:
        raise HTTPException(
            status_code=400,
            detail=(
                "Unsupported report type. "
                "Use compliance or tender_summary."
            ),
        )

    query = db.query(TenderAnalysis)

    if tender_id is not None:
        tender = (
            query
            .filter(TenderAnalysis.id == tender_id)
            .first()
        )
    else:
        tender = (
            query
            .order_by(TenderAnalysis.created_at.desc())
            .first()
        )

    if not tender:
        raise HTTPException(
            status_code=404,
            detail="No tender analysis found.",
        )

    if type == "compliance":
        title = (
            f"Compliance Report - "
            f"{tender.filename or f'Tender {tender.id}'}"
        )
    else:
        title = (
            f"Tender Summary - "
            f"{tender.filename or f'Tender {tender.id}'}"
        )

    content = build_report_content(tender)

    report = Report(
        tender_id=tender.id,
        report_type=type,
        title=title,
        content=content,
    )

    db.add(report)
    db.commit()
    db.refresh(report)

    return serialize_report(report)


@router.get("/{report_id}")
def get_report(
    report_id: int,
    db: Session = Depends(get_db),
):
    report = (
        db.query(Report)
        .filter(Report.id == report_id)
        .first()
    )

    if not report:
        raise HTTPException(
            status_code=404,
            detail="Report not found.",
        )

    return serialize_report(report)


@router.get("/{report_id}/download")
def download_report(
    report_id: int,
    db: Session = Depends(get_db),
):
    report = (
        db.query(Report)
        .filter(Report.id == report_id)
        .first()
    )

    if not report:
        raise HTTPException(
            status_code=404,
            detail="Report not found.",
        )

    tender = None

    if report.tender_id:
        tender = (
            db.query(TenderAnalysis)
            .filter(TenderAnalysis.id == report.tender_id)
            .first()
        )

    if tender:
        pdf = build_tender_pdf(tender)
    else:
        pdf = build_text_pdf(report.title, report.content)

    filename = (
        f"BISQ-report-{report.id}.pdf"
    )

    return Response(
        content=pdf,
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                f'attachment; filename="{filename}"'
            )
        },
    )