import { useNavigate } from "react-router-dom";
import { AlertTriangle, CheckCircle2, XCircle } from "lucide-react";
import { tenders } from "../data/mockTenders.js";

const ICON = {
  ok: <CheckCircle2 size={14} className="v-ok" />,
  warn: <AlertTriangle size={14} className="v-warn" />,
  error: <XCircle size={14} className="v-error" />,
};

export default function Compliance() {
  const navigate = useNavigate();

  const findings = tenders.flatMap((t) =>
    t.validation.map((v, i) => ({ ...v, tender: t, key: `${t.id}-${i}` }))
  );

  const counts = findings.reduce(
    (acc, f) => ({ ...acc, [f.type]: (acc[f.type] || 0) + 1 }),
    {}
  );

  return (
    <>
      <div className="page-header">
        <div>
          <div className="eyebrow">COMPLIANCE</div>
          <h1>Compliance</h1>
          <p>Review compliance findings and evidence across all tenders.</p>
        </div>
      </div>

      <div className="stats">
        <div className="stat">
          <div className="stat-label">PASSED CHECKS</div>
          <div className="stat-number">{counts.ok || 0}</div>
          <div className="stat-note positive">No action needed</div>
        </div>
        <div className="stat">
          <div className="stat-label">WARNINGS</div>
          <div className="stat-number">{counts.warn || 0}</div>
          <div className="stat-note">Recommend review</div>
        </div>
        <div className="stat danger">
          <div className="stat-label">CRITICAL FINDINGS</div>
          <div className="stat-number danger-number">{counts.error || 0}</div>
          <div className="stat-note danger-text">Requires attention</div>
        </div>
      </div>

      <section className="table-card">
        <div className="table-header">
          <div>
            <h2>All Findings</h2>
            <p>Generated by the Validation / Rule Engine</p>
          </div>
        </div>

        <div className="validation-list" style={{ padding: "6px 17px 17px" }}>
          {findings.map((f) => (
            <div
              className="validation-row clickable"
              key={f.key}
              onClick={() => navigate(`/tenders/${f.tender.id}`)}
            >
              {ICON[f.type]}
              <span>
                {f.text}
                <small className="finding-source"> — {f.tender.name}</small>
              </span>
            </div>
          ))}
        </div>
      </section>
    </>
  );
}
