from datetime import datetime
from html import escape
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)


STATUS_COLORS = {
    "COMPLIANT": colors.HexColor("#15803d"),
    "NON_COMPLIANT": colors.HexColor("#b91c1c"),
    "NEEDS_EVIDENCE": colors.HexColor("#b45309"),
    "PARTIAL": colors.HexColor("#b45309"),
}


def clean(value):
    """Escape text so it is safe inside a reportlab Paragraph."""

    if value is None:
        return ""

    text = str(value).replace("\r\n", "\n").replace("\r", "\n")

    return escape(text).replace("\n", "<br/>")


def build_styles():
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "BisqTitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            alignment=TA_LEFT,
            spaceAfter=4,
            textColor=colors.HexColor("#0f172a"),
        ),
        "meta": ParagraphStyle(
            "BisqMeta",
            parent=base["Normal"],
            fontSize=9.5,
            leading=14,
            textColor=colors.HexColor("#64748b"),
        ),
        "heading": ParagraphStyle(
            "BisqHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            spaceBefore=18,
            spaceAfter=6,
            textColor=colors.HexColor("#0f172a"),
        ),
        "subheading": ParagraphStyle(
            "BisqSubheading",
            parent=base["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            spaceBefore=10,
            spaceAfter=2,
            textColor=colors.HexColor("#1e293b"),
        ),
        "label": ParagraphStyle(
            "BisqLabel",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            spaceBefore=6,
            spaceAfter=1,
            textColor=colors.HexColor("#475569"),
        ),
        "body": ParagraphStyle(
            "BisqBody",
            parent=base["Normal"],
            fontSize=10,
            leading=14.5,
            textColor=colors.HexColor("#1f2937"),
        ),
        "mono": ParagraphStyle(
            "BisqMono",
            parent=base["Normal"],
            fontName="Courier",
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#1f2937"),
        ),
        "status": ParagraphStyle(
            "BisqStatus",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
        ),
    }

    return styles


def draw_page_furniture(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#94a3b8"))

    canvas.drawString(
        doc.leftMargin,
        12 * mm,
        "Generated by BISQ",
    )

    canvas.drawRightString(
        doc.pagesize[0] - doc.rightMargin,
        12 * mm,
        f"Page {canvas.getPageNumber()}",
    )

    canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
    canvas.setLineWidth(0.5)

    canvas.line(
        doc.leftMargin,
        16 * mm,
        doc.pagesize[0] - doc.rightMargin,
        16 * mm,
    )

    canvas.restoreState()


def render_pdf(story, title):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=22 * mm,
        title=title,
        author="BISQ",
    )

    doc.build(
        story,
        onFirstPage=draw_page_furniture,
        onLaterPages=draw_page_furniture,
    )

    pdf = buffer.getvalue()
    buffer.close()

    return pdf


def build_header(styles, heading, tender_name, analysis_id):
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    meta_lines = [f"<b>Tender:</b> {clean(tender_name)}"]

    if analysis_id is not None:
        meta_lines.append(f"<b>Analysis ID:</b> {clean(analysis_id)}")

    meta_lines.append(f"<b>Generated:</b> {generated_at}")

    return [
        Paragraph(clean(heading), styles["title"]),
        HRFlowable(
            width="100%",
            thickness=2,
            color=colors.HexColor("#0f172a"),
            spaceBefore=4,
            spaceAfter=8,
        ),
        Paragraph("<br/>".join(meta_lines), styles["meta"]),
    ]


def build_finding_block(styles, index, finding):
    requirement = finding.get("requirement", "")
    assessment = finding.get("assessment", "")
    evidence = finding.get("evidence", "")
    source = finding.get("source", "")
    page = finding.get("page")

    block = [
        Paragraph(f"Finding {index}", styles["subheading"]),
        HRFlowable(
            width="100%",
            thickness=0.5,
            color=colors.HexColor("#e2e8f0"),
            spaceBefore=2,
            spaceAfter=4,
        ),
        Paragraph("REQUIREMENT", styles["label"]),
        Paragraph(clean(requirement) or "&mdash;", styles["body"]),
        Paragraph("ASSESSMENT", styles["label"]),
        Paragraph(clean(assessment) or "&mdash;", styles["body"]),
        Paragraph("EVIDENCE", styles["label"]),
        Paragraph(clean(evidence) or "&mdash;", styles["body"]),
    ]

    footnotes = []

    if source:
        footnotes.append(f"<b>Source:</b> {clean(source)}")

    if page is not None:
        footnotes.append(f"<b>Page:</b> {clean(page)}")

    if footnotes:
        block.append(Spacer(1, 4))
        block.append(
            Paragraph(" &nbsp;&nbsp;|&nbsp;&nbsp; ".join(footnotes), styles["meta"])
        )

    block.append(Spacer(1, 10))

    return block


def build_source_block(styles, index, source):
    number = (
        source.get("is_number")
        or source.get("document_id")
        or "Unknown"
    )

    title = source.get("title")
    year = source.get("year")
    page = source.get("page_number")
    pdf_url = source.get("pdf_url")

    block = [
        Paragraph(
            f"Source {index}: {clean(number)}",
            styles["subheading"],
        )
    ]

    details = []

    if title:
        details.append(f"<b>Title:</b> {clean(title)}")

    if year:
        details.append(f"<b>Year:</b> {clean(year)}")

    details.append(
        f"<b>Page:</b> {clean(page) if page is not None else 'N/A'}"
    )

    if pdf_url:
        safe_url = clean(pdf_url)
        details.append(
            f'<b>PDF:</b> <link href="{safe_url}" color="#0645ad">'
            f"{safe_url}</link>"
        )

    block.append(Paragraph("<br/>".join(details), styles["body"]))
    block.append(Spacer(1, 8))

    return block


def build_tender_pdf(tender):
    """Render a full compliance report PDF for a tender analysis."""

    styles = build_styles()

    findings = tender.findings or []
    sources = tender.sources or []

    status = tender.status or "NEEDS_EVIDENCE"

    status_style = ParagraphStyle(
        "BisqStatusValue",
        parent=styles["status"],
        textColor=STATUS_COLORS.get(
            status.upper(),
            colors.HexColor("#0f172a"),
        ),
    )

    story = build_header(
        styles,
        "BISQ Compliance Report",
        tender.filename or "Untitled Tender",
        tender.id,
    )

    story.append(Paragraph("Overall Status", styles["heading"]))
    story.append(
        Paragraph(clean(status).replace("_", " "), status_style)
    )

    story.append(Paragraph("Summary", styles["heading"]))
    story.append(
        Paragraph(
            clean(tender.summary) or "No summary available.",
            styles["body"],
        )
    )

    story.append(Paragraph("Findings", styles["heading"]))

    if not findings:
        story.append(
            Paragraph("No findings were generated.", styles["body"])
        )
    else:
        for index, finding in enumerate(findings, start=1):
            story.append(
                KeepTogether(
                    build_finding_block(styles, index, finding)
                )
            )

    story.append(Paragraph("BIS Sources", styles["heading"]))

    if not sources:
        story.append(
            Paragraph("No BIS sources available.", styles["body"])
        )
    else:
        for index, source in enumerate(sources, start=1):
            story.append(
                KeepTogether(
                    build_source_block(styles, index, source)
                )
            )

    return render_pdf(story, "BISQ Compliance Report")


def build_text_pdf(title, content):
    """Fallback PDF for reports with no linked tender analysis."""

    styles = build_styles()

    story = build_header(styles, title, title, None)

    story.append(Spacer(1, 12))

    for paragraph in (content or "").split("\n\n"):
        if not paragraph.strip():
            continue

        story.append(Paragraph(clean(paragraph), styles["mono"]))
        story.append(Spacer(1, 8))

    return render_pdf(story, title)
